### PR TITLE
Fixes #102 UTC Event Timezone Fix

### LINKED ISSUE #102: "Join us" page shows next month's meetup the day of
https://twitter.com/zachhale/status/529807065867239424

### PR DESCRIPTION
**Pull request by TLynam**
- Set app timezone to pst
- Use Date.current instead of Date.today so it'll use pst timezone

### CODE REVIEW

**Comment by phiggins** [comment]
Thanks for looking into this @TLynam! I have a few notes:

* It looks like there's a few somewhat unrelated changes in here. Are all of them necessary to fix the bug?
* Did you figure out exactly what the bug was in the first place? Is there a way I can test it to verify it's fixed?
* It looks like some tests failed on TravisCI because of the changes you made in the Event model. It would be nice to get that fixed before we merge this.

If you're at the next hack night we can chat about this. Thanks again for taking a crack at it!

**Comment by TLynam** [comment]
Thanks @phiggins!

I updated so it's more straightforward.  I was able to reproduce by setting my laptop timezone to UTC early AM Wed Feb 4th.  This is still the first Tuesday of the month pst time.  It works for me if I set the app default timezone to pst and also use Date.current instead of Date.today.  Date.current is Time.zone.today and will show Tuesday whereas Date.today will pull the system UTC time.

**Comment by zenspider** [comment]
Looks good to me. @thagomizer ?

**Comment by phiggins** [comment]
I'm willing to give this a shot. Sorry for taking so long @TLynam!

**Pull request merged**
